### ISSUE TITLE
[Suggestion] DE-OXIDIZE COPPER

### ISSUE THREAD

**Issue by Aruman-Zen** [purejosh/purecoppertools#7]
I was looking into your mod and i found out that it can't oxidize tools and armor normally (because ticks and such), i know this is intended but maybe you could make it so we can DE-OXIDIZE tools and amor with an axe and anvil (or something involving the axe), since you can already in vanilla use the axe to DE-OXIDIZE blocks (i know oxidized tools are better but it would be cool as a mechanic)
image example of epic DE-OXIDIFICATION:
![image](https://github.com/purejosh/purecoppertools/assets/159113965/3af34671-84c1-44c6-a753-5262aa3f3341)

as for oxidizing the items, maybe you could consider throwing the copper tools and armor into a cauldron or right clicking a cauldron (maybe you should dip the tools a number of times to work, wasting water)
incredibly dangerous example of dipping things into water:
![image](https://github.com/purejosh/purecoppertools/assets/159113965/88d529b6-9464-4ccb-842d-cc1bf81848ca)

anyways thanks for reading, i hope you atleast consider the DE-OXIDIZING system

**Comment by purejosh** [comment]
So, a couple of things I want to consider is compatibility and resource friendliness. Right clicking when tied to a vanilla item would require me to listen to all right clicks, whereas right clicking with a modded item is easier on the processing. 

I could add a recipe to "scrape" the items, but I'm less enthused about that. A recipe for every item in my mod can get extensive.

Another developer I was talking to pointed out that water and gunpowder can be used as a way to oxidize items. I may consider using that.

**Comment by Aruman-Zen** [comment]
well that sounds like a plan, would be really nice to have a way to oxidize the items, i was thinking of some more ways that could work so here are some:

1. use a wet sponge to oxidize
2. receive explosion damage
3. brew in the brewing stand with gunpowder (dont know how hard it would be)
4. make a custom item that oxidizes copper (a potion or something)
5. leave armor in a armor stand and have it oxidize? (dont know if this would cause lag, maybe leave the tools in a campfire or something)
6. specific timer (not sure if this is still ticks but after like 10 minutes it would oxidize)

besides that i can't think of more ways that wouldn't be overly complicated since is not that usefull to oxidize copper since you could get diamonds instead, i hope you can make it work since it would be really cool, good luck!

**Comment by purejosh** [comment]
After some thought, I've decided to not include an of these proposed features. Reason being, in order to convert one armor/item to another, any data components (durability, enchantments, name, etc) would need to be carried over, and I'm fairly certain only the smithing table would be able to perform this. That would never work. A smithing table requires a template and an item, so using three materials to convert an item to another oxidization state is a feature no one would use. 

I could write code to essentially migrate the data from one item to another, upon a certain event such as a lightning strike, but recipes of any sorts in any block other than the smithing table wouldn't be possible. I will keep this in mind in future releases, but as of now, I'm not a skilled enough developer to add such features. 

I genuinely appreciate the feedback, they're great ideas. I hope to implement them in the future.
